BEGIN;

TRUNCATE TABLE "users" CASCADE();
TRUNCATE TABLE "oauth" CASCADE();
TRUNCATE TABLE "role" CASCADE();
TRUNCATE TABLE "products" CASCADE();
TRUNCATE TABLE "categories" CASCADE();
TRUNCATE TABLE "products_categories" CASCADE();
TRUNCATE TABLE "images" CASCADE();
TRUNCATE TABLE "orders" CASCADE();
TRUNCATE TABLE "products_orders" CASCADE();

SELECT SETVAL 

COMMIT;